spring.application.name=.

spring.datasource.url=jdbc:mysql://localhost:3306/morago
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=5f2c3d8a1e7b9f6a4c8d2e5f7a1b3c9d5e6f8a2b4c7d9e1f3a5b7c9d2e4f6a8

cors.allowed-origins=http://localhost:3000,http://localhost:5173

spring.profiles.active=dev